{% set name = "dask-drmaa" %}
{% set version = "0.1.1" %}
{% set sha256 = "999f8e037c3cfd56a885eb9b15bfb06e552bf37292c1434e153a8f4527afb644" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - dask-drmaa = dask_drmaa.cli.dask_drmaa:go

requirements:
  build:
    - python
    - pip

  run:
    - python
    - dask-core
    - distributed >=1.20.0
    - drmaa
    - click

about:
  home: https://github.com/dask/dask-drmaa
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: Dask on DRMAA

  dev_url: https://github.com/dask/dask-drmaa

extra:
  recipe-maintainers:
    - jakirkham
    - mrocklin
