{% set name = "dask-drmaa" %}
{% set version = "0.2.0" %}
{% set sha256 = "8bc9a730d5cd7f9b1d9541f1076c2300f5590f09c6c38b0f3d2d21b00852c746" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - dask-drmaa = dask_drmaa.cli.dask_drmaa:go

requirements:
  build:
    - python
    - pip

  run:
    - python
    - dask-core
    - distributed >=1.21.3
    - drmaa
    - click

about:
  home: https://github.com/dask/dask-drmaa
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: Dask on DRMAA

  dev_url: https://github.com/dask/dask-drmaa

extra:
  recipe-maintainers:
    - jakirkham
    - mrocklin
