travis:
  secure:
    BINSTAR_TOKEN: VI8NjFDfkrcDfIM/4rMOwjm3DLwqBt+anVdkajL/jr8wgqWtAbb3cuFC/bqbvtZPaXAoRTGo/LGNM4hD57vmlOvB/dvX8pTqUIc7VfAXXtzlaVbPTbiZfaILwzI+edauDabYEmecBcQ9D1D+2Eo4Rq773ji13pPB+v4798G9k/7xmVjLXclXewaTgY/YCH6Hiu62XyVnM9IipIAgsB3wB5znplrlsaxk3ZzQ6krrJfm402wDFjZTs8CO4Lia0pA96xZFiXnLLrstMiixtBGRFwDxlfF5PlX5Bqgn3x8HMvJtVIU7IbNaS8cNG3Do54cVsGaV67ozQGSQ4D0bG0oDvpAuWZVIkECOZIu0RcOgy8pS/DsIZ0qnGxPCL/ad1AYPt0Asb+DvTXEL7pWqIkofA3u9rwqLF+Z2K8NMyI6WCacfC1C2jewfZ8k86dTlGN1euGiZi5YnFrLGvkSjp1PGlpUpNc9Dx6EaxFWf/HI5NhpGoZWZki43G0bT+yc/XWksjNPtxWZlkO8HJRxa5eOSB3MDnogcWsHwy8N3Bq77hvp6nC3Lq6TVTfgsb+8RB+AdovoECoxvs6ywJXBwUR2eOJY4p4vf7To7EqEHJeWQy88RphZIImtG/b8NNGcaIow76WddZh1jKeVrF4TjYIpeJRQAEffFmGftbCIo484Lhho=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
