travis:
  secure:
    BINSTAR_TOKEN: TgNapSWAdso7sF4Oo+en2ZmzAnabUOt6NtzFXr4aIVoy3eAvoGmwe6tbt/joC7BXQXZx0eUD4EGaEyoNoB8D9uM4MaIebE0BP7qZNyqIYdP6C84meNxA56W53qI4E832mwhrCDWY16JIPmGJU6BgoCadMHO9XQgpvUeNF1FNKN2HIO24JpLeSxAORkHsW28Dxid0iVzHnNIhxUw6MLUoed+RTXaU+L1G7uZc+edoy8v/07Kv8yLFnqgi5uP4Mt4V+heGD+ShWd37XRdWFZgcHfpGsrG3oCJatbnjFaS2s+tf7xr/haYaSnL2uLNPHsDw1S4SyGmnzibw9R6hhTDnZsTb8EJJtHt3LHI5uh39x4buEhnS21eYaMiUnjHKlgLjPy/RLWglLk6IOIpWxS0rwMy3dsFMKIL+5NXPeDJVfqXLfkw6WHB9r2rvAKEGSsISzSQ4tltVcORyfC4aAz9Z24iXxifrsndfxTmh82fJQtzWt7l75+92EZMlGEuXGgpaa0p5RWISlrImzAoTYhU4e/4kAcSw6/78ZDzlCB72foKfEfuwAoV1zp4CIqP26KzltH2/gJWSH+bo6WMwHaIfT/elE1xv91YwV1kMIoyOkHUrwOnfLEggVICElDnl/RQlPZxWdZvB+JcLUQjlqqAZzq2Y2QyK7Ehzoo0JcJeTUA8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
